name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # - name: Install Git
      #   run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          path: ./web-app
          fetch-depth: 1 # Use a shallow clone to speed up the checkout
          submodules: "none" # Disable fetching submodules

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.18.0"
          working-directory: ./web-app

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your actual build script
